---
title: "cellbrowser"
author: "Kent Riemondy RBI"
date: "2/27/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Cellbrowser

Format seurat object into a cellbrowser directory suitable for html browser. 

```{r}
source("../../R/globals.R")
library(tidyverse)
expts <- c("Sorted", "Reaggregated")

bcells <- map(expts, 
     ~readRDS(paste0(., "_final.rds")))

names(bcells) <- expts

```

Simplify object metadata to make interpretable

```{r}

cols <- map(bcells, ~colnames(.x@meta.data))

cols_to_keep <- c(
  `genes per cell` = "nGene",
  `UMIs per cell` = "nUMI",
  `experiment name` = "expt",
  `proporition of UMIs as mitochondria` = "proportion_mito",
  `clusters` = "res.0.5",
  `cell_types` = "cell_type",
  `pseudotime` = "Pseudotime",
  `pseudotime state` = "State", 
  `velocity endpoint probability` = "endpoints_imputed",
  `velocity startpoint probability` = "startpoints_imputed")

bcells <- map(bcells, function(sobj){
  sobj@meta.data <- sobj@meta.data[, cols_to_keep]
  colnames(sobj@meta.data) <- names(cols_to_keep)
  sobj@meta.data$cell_types <- str_replace(sobj@meta.data$cell_types, ",", "")
  Idents(sobj) <- "cell_types"
  sobj
})
```


Split into 2 objects and save rds files


```{r}
outdir <- "cellbrowser"
dir.create(outdir, showWarnings = FALSE)

# write out rds files with names listed in sobjs
iwalk(bcells, ~saveRDS(.x, 
                   file.path(outdir, 
                                 paste0(.y, ".rds"))))
```

## Set colors

```{r}

## default palette (see ../../R/globals.R)
col_palette <- discrete_palette_default

# requested cell type palette
vec <- brewer.pal(9, "RdYlGn")
sorted_colmap <- get_high_low(vec, 7)
names(sorted_colmap) <- c(
  "Mature (INS+, IAPP+)",
  "Igf2+",
  "Immature (FEV+)",
  "Beta subpopulation 2 and 4 (CD9+)",
  "Proliferating (MKI67+)",
  "Polyhormonal (GCG+)",
  "Polyhormonal (SST+)"
)


reagg_colmap <- get_high_low(vec, 7)
names(reagg_colmap) <- c(
  "Mature (INS+)",
  "Mature (INS+, IAPP+)",
  "Immature (FEV+)",
  "Immature (VIM+)",
  "Polyhormonal (GCG+)",
  "Polyhormonal (SST+)",
  "Unknown celltype"
)

## summarize per cluster annotations
to_map <- c("cell_types", 
            "clusters",
            "experiment name", 
            "pseudotime state")

col_maps <- map(bcells, ~as.list(.x@meta.data[, to_map]) %>%
      map(~as.character(unique(.x))))

col_maps <- map2(col_maps, list(sorted_colmap, reagg_colmap), 
                 function(x, colmap){
  res <- list()
  res$cell_types <- colmap
  
  tmp <- col_palette[1:length(x$clusters)]
  names(tmp) <- x$clusters
  res$clusters <- tmp 

  tmp <- col_palette[1:length(x$`experiment name`)]
  names(tmp) <- x$`experiment name`
  res$`experiment name` <- tmp 
  
  tmp <- col_palette[1:length(x$`pseudotime state`)]
  names(tmp) <- x$`pseudotime state`
  res$`pseudotime state` <- tmp 
  
  res
})


imap(col_maps, 
    ~map_dfr(.x, ~tibble(clusterName = str_replace(names(.x), ",", ""), 
                  color = .x)) %>% as.data.frame() %>% 
  write_csv(paste0(.y, "_colorMap.csv"), col_names = F, quote_escape = "none"))

imap(col_maps, 
    ~map_dfr(.x, ~tibble(clusterName = names(.x), 
                  color = .x)) %>% as.data.frame() %>% 
  write_tsv(paste0(.y, "_colorMap_with_commas.tsv"), col_names = F, quote_escape = "none"))
```


Build cellbrowser objects. Note requires UCSC (`cellbrowser python package`[ https://cellbrowser.readthedocs.io/index.html])

```{r}
dir.create("cellbrowser/markers", recursive = TRUE)

pwalk(list(bcells, names(bcells), c("seBCs", "eBCs")), function(x, id, type) {
  cols <- colnames(x@meta.data)
  names(cols) <- colnames(x@meta.data)

  mkrs <- read_tsv(paste0("../2018-12-19_figs/marker_tables/",
                          id, 
                          "_markers_cell_type.txt")) %>% 
  select(cluster, gene, p_val_adj, everything())

  write_tsv(mkrs, paste0("cellbrowser/markers/", 
                         id, "_markers.tsv"))

  do.call(function(...) {ExportToCellbrowser(x, 
                    dir = file.path("cellbrowser", id),
                    dataset.name = type,
                    reductions = c("tsne", "ptime"),
                    markers.file = paste0("cellbrowser/markers/", 
                                          id, 
                                          "_markers.tsv"),
                    cluster.field = "cell_types",
                    ...)}, 
        as.list(cols))
})
```



```{bash}
cd cellbrowser

echo -e '\ncolors="/Users/kriemo/Projects/sc_repos/sebeta/results/2018-12-19_figs/Sorted_colorMap.csv"' >> Sorted/cellbrowser.conf

echo -e '\ncolors="/Users/kriemo/Projects/sc_repos/sebeta/results/2018-12-19_figs/Reaggregated_colorMap.csv"' >> Reaggregated/cellbrowser.conf
```


```{bash}
cd cellbrowser

/miniconda3/bin/cbBuild \
-i Sorted/cellbrowser.conf \
-i Reaggregated/cellbrowser.conf \
-i ../../2019-05-23_public_data/cellbrowser/cellbrowser.conf \
-o beta

```


