---
title: "additional pseudotime analysis"
author: "Kent Riemondy RBI"
date: "4/17/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Pseudotime


```{r}
source("../../R/globals.R")
library(tidyverse)
library(monocle)
expts <- c("Sorted", "Reaggregated")

bcells <- map(expts, 
     ~readRDS(paste0(., "_final.rds")))

names(bcells) <- expts

atms <- map(expts, ~readRDS(paste0(.x, "_pt.rds")))
names(atms) <- expts
```


```{r}

plot_cell_trajectory(atms$Sorted, color_by = "Pseudotime")

# subset to cells along trajectory of interest (not proliferating or subpopulation 2 and 4 (cd(+)))

to_keep <- c("Mature (INS+, IAPP+)",
  "Polyhormonal (GCG+)",
  "Igf2+",
  "Immature (FEV+)",
  "Polyhormonal (SST+)")

subset_dat <- atms$Sorted[, which(pData(atms$Sorted)$cell_type %in% to_keep)]

diff_test_res <- differentialGeneTest(subset_dat,
                 fullModelFormulaStr = "~sm.ns(Pseudotime)", 
                 cores = 6)

saveRDS(diff_test_res, "pseudotime/diff_genes.rds")

diff_test_res <- readRDS("pseudotime/diff_genes.rds")
sig_gene_names <- row.names(subset(diff_test_res, qval < 0.01))
sig_genes <- subset(diff_test_res, qval < 0.01)



# get data to plot ourselves
# see plot_pseudotime_heatmap source code
scale_max <- 3
scale_min <- -3
num_clusters <- 2
cds_subset <- subset_dat[which(rownames(subset_dat) %in% sig_gene_names), ]

newdata <- data.frame(Pseudotime = seq(min(pData(cds_subset)$Pseudotime),
                                       max(pData(cds_subset)$Pseudotime),
                                       length.out = 100)) 
 
m <- genSmoothCurves(subset_dat[sig_gene_names, ], 
                         cores = 3,
                         trend_formula = '~sm.ns(Pseudotime, df=3)',
                         relative_expr = T,
                         new_data = newdata)


m <- m[!apply(m,1,sum)==0,]
m <- log10(m+1)
                 
m <- m[!apply(m,1,sd)==0,]
m <- Matrix::t(scale(Matrix::t(m),center=TRUE))
m <- m[is.na(row.names(m)) == FALSE,]
m[is.nan(m)] <- 0
m[m>scale_max] <- scale_max
m[m<scale_min] <- scale_min


row_dist <- as.dist((1 - cor(Matrix::t(m)))/2)
row_dist[is.na(row_dist)] <- 1
hdist_clust <- hclust(row_dist)

annotation_row <- data.frame(Cluster=factor(cutree(hdist_clust, num_clusters)))

hmap_dat <- list(clusters = annotation_row, 
                 matrix = m)
saveRDS(hmap_dat, "pseudotime/hmap_dat.rds")
hmap_dat <- readRDS("pseudotime/hmap_dat.rds")
annotation_row <- hmap_dat$clusters
m <- hmap_dat$matrix

to_highlight <- c(
        "FEV",
        "ENTPD3",
        "GCG",
        "SST",
        "IAPP",
        "INS",
        "DLK1",
        "LMO1",
        "APOC3",
        "CD99",
        "APOA1"
)

library(ComplexHeatmap)

hmap <- Heatmap(m, 
        col = viridis(256), 
        name = "Z-score",
        show_row_names = FALSE, 
        show_column_names = FALSE, 
        cluster_columns = FALSE,
        split = annotation_row$Cluster, 
        show_row_dend = FALSE, 
        show_column_dend = FALSE) +
rowAnnotation(link = anno_mark(at = which(rownames(m) %in% to_highlight), 
        labels = rownames(m)[which(rownames(m) %in% to_highlight)], 
        labels_gp = gpar(fontsize = 10), padding = 0.5))

hmap

pdf("pseudotime/hmap_sorted.pdf", width =7, height = 7)
draw(hmap)
dev.off()
```

```{r}
sig_gene_top <- merge(sig_genes, annotation_row, by = 0) %>% 
        dplyr::rename(gene = Row.names) %>% 
        group_by(Cluster) %>% 
        arrange(qval, .by_group = TRUE) %>% 
        slice(1:10)

plts <- map(sig_gene_top$gene,
    ~plot_genes_in_pseudotime(subset_dat[which(rownames(subset_dat) %in% .x), ],
                          color_by = "cell_type"))

plt <- plot_grid(plotlist = plts, nrow = 6, ncol = 5)
save_plot("pseudotime/ptime_plots.pdf", plt, nrow = 6, ncol = 5, base_asp = 2)
```


```{r}
selected_genes <- c(
  "ENTPD3",
  "egfp",
  "FEV",
  "DLK1"
)
plts <- map(selected_genes,
    ~plot_genes_in_pseudotime(subset_dat[which(rownames(subset_dat) %in% .x), ],
                          color_by = "cell_type"))

plt <- plot_grid(plotlist = plts, nrow = 2, ncol = 2)
save_plot("pseudotime/ptime_various_plots.pdf", plt, nrow = 2, ncol = 2, base_asp = 2)
```


