---
title: "pseudotime"
author: "Kent Riemondy RBI"
date: "`r Sys.Date()`"
bibliography: "/Users/kriemo/Projects/russ/docs/bibliography.bib"
output:
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: false
    fig_caption: yes
    fig_retina: 1 
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(cache.lazy = FALSE)
```


```{r libs, message=FALSE, warning=FALSE, echo=FALSE}
source("../../R/globals.R")
library(monocle)
tcols <- rev(brewer.pal(11, "RdGy")[c(1:5, 7)])[c(1,6)]

bcells <- readRDS(file.path(results_dir, 
                            "2018-05-30", 
                            "sobj.rds"))

b_markers <- read_tsv(file.path(results_dir, 
                            "2018-05-30", 
                            "res0.3_markers.txt"))

bcells <- SetAllIdent(bcells, "res0.3")
```


```{r, eval = F}
atm <- importCDS(bcells)
atm <- estimateSizeFactors(atm)
atm <- estimateDispersions(atm)

# select_genes
atm <- detectGenes(atm, min_expr = 0.1)
fData(atm)$use_for_ordering <- fData(atm)$num_cells_expressed > 0.05 * ncol(atm)
plot_pc_variance_explained(atm, return_all = F)

atm <- reduceDimension(atm,
                       max_components = 2,
                       norm_method = 'log',
                       num_dim = 15,
                       reduction_method = 'tSNE',
                       verbose = T)

atm <- clusterCells(atm, verbose = F, num_clusters = 5)

plot_rho_delta(atm, rho_threshold = 2, delta_threshold = 4 )
atm_expressed_genes <-  row.names(subset(fData(atm),
                                         num_cells_expressed >= 10))

clustering_DEG_genes <- differentialGeneTest(atm[atm_expressed_genes,],
                                             fullModelFormulaStr = '~Cluster',
                                             cores = 4)

atm_ordering_genes <- row.names(clustering_DEG_genes)[order(clustering_DEG_genes$qval)][1:1000]

atm <- setOrderingFilter(atm,
                         ordering_genes = atm_ordering_genes)

atm <- reduceDimension(atm, method = 'DDRTree')


atm <- orderCells(atm, root_state = 1)


saveRDS(atm, "pt.rds")
```


```{r}

atm <- readRDS("pt.rds")

plot_cell_trajectory(atm, color_by = "Pseudotime") +
    scale_colour_viridis(discrete = F)

plot_cell_trajectory(atm, color_by = "res.0.3") +
    scale_colour_brewer(palette = "Paired")

plot_cell_trajectory(atm, color_by = "State") +
    scale_colour_viridis(discrete = T)
```


```{r}

control_markers <- c(
  "CD9",
  "ST8SIA1",
  "INS",
  "NPY",
  "KCNE4",
  "HCN1",
  "DAB1",
  "ST8SIA1",
  "HCN4",
  "NEUROD1",
  "SCGB2A1",
  "KLHL1",
  "SLC44A4",
  "GCG", # alpha cells glucagon
  "IAPP", # beta cells amylin,
  "SST", #delta cells Somatostatin
  "PPY", #PP cells  (gamma cells or F cells) pancreatic polypeptide
  "GHRL" #Epsilon cells
)

map(control_markers,
    ~plot_cell_trajectory(atm, 
                     markers = .x, 
                     use_color_gradient = T, 
                     option = "C", 
                     cell_size =  0.75))
```


### BEAM
```{r branchpoint_analysis, fig.width= 8, fig.height= 16, eval = }
atm <- readRDS("pt.rds")

if (!file.exists("beam.rds")) {
  BEAM_inj <- BEAM(atm, branch_point = 1, cores = 4)
  BEAM_inj <- BEAM_inj[order(BEAM_inj$qval),]
  BEAM_inj <- BEAM_inj[,c("gene_short_name", "pval", "qval")]
  saveRDS(BEAM_inj, "beam.rds")
} else {
  BEAM_inj <- readRDS("beam.rds")
}
```


```{r heatmap, fig.width= 8, fig.height= 16}

pdf("beam.pdf", width = 8, height = 36)
plot_genes_branched_heatmap(atm[row.names(BEAM_inj[1:300, ]),],
                                          branch_point = 1,
                                          num_clusters = 4,
                                          use_gene_short_name = TRUE,
                                          show_rownames = TRUE)
dev.off()


```


## Plot psuedotime on tSNE

```{r}

mdata <- pData(atm) %>% 
  tibble::rownames_to_column("cell") %>% 
  left_join(tibble::rownames_to_column(bcells@meta.data, "cell"),
            .) %>% 
  dplyr::select(cell, Pseudotime, State) %>% 
  tibble::column_to_rownames("cell")

bcells <- AddMetaData(bcells, mdata)

plot_feature(bcells, gene = "Pseudotime", meta_data_col = T)

saveRDS(bcells, "pt_sobj.rds")
```


